---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

manageNodeGroup:
  - name: spot-instances
    instanceType: m5.large
    desiredCapacity: 3
    spot: true
