apiVersion: v1
kind: Pod
metadata:
  name: secret-pod

spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
        - secretRef:
            name: secret-conf


# kubectl apply -f secretsdemopod.yaml
# kubectl exec -it secret-pod -- bash
# env