apiVersion: v1
kind: Pod
metadata:
  name: "env-demo-direct from-pod"
  labels:
    purpose: "env-varibales-from-pod"

spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

      env:
        - name: course
          value: devops

        - name: duraton
          value: "3 Hrs"

          