apiVersion: v1
kind: pod
metadata:
  name: "env-vars-demo"
  labels:
    purpose: env-demo-purpose

spec:
  containers:
    - name: cnter1
      image: nginx
      ports:
        - containerPort: 80

      env:
        - name: course
          value: "devops"
        
        - name: trainer
          value: "raja sekahr Reddy"



# kubectl apply -f environmentvars.yaml
# kubectl get pods
# kubectl exec -it env-demo-purpose -- bash
# and then type  env --> to see the list of environment varaiables


